const item_data = [
    {
        "id":"1",
        "points":"1",
        "name":"unu",
        "image":[require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default],
        "gen":"woman",
        "category":["imbracaminte","sweat","hanorace","one","two"],
        "price":"10",
        "colorname":"black",
        "color":["000000", "ff0000","800080"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"2",
        "points":"1",
        "name":"doi",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie2.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie3.jpg').default,require('./images/hoodie4.jpg').default,require('./images/hoodie5.jpg').default],
        "price":"20",
        "colorname":"red",
        "color":["000000","ff0000","800080","ff00e6","32a852", "173a99","d16a47","998817"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"2",
        "points":"1",
        "name":"doi",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie3.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default],
        "price":"22",
        "colorname":"green",
        "color":["ff0000","800080","ff00e6","32a852", "173a99","d16a47","998817","000000"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"2",
        "points":"1",
        "name":"doi",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie4.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default],
        "price":"23",
        "colorname":"green",
        "color":["800080","ff00e6","32a852", "173a99","d16a47","998817","000000","ff0000"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"2",
        "points":"1",
        "name":"doi",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie5.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default],
        "price":"24",
        "colorname":"purple",
        "color":["ff00e6","32a852", "173a99","d16a47","998817","000000","ff0000","800080"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"2",
        "points":"1",
        "name":"doi",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie6.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default],
        "price":"20",
        "colorname":"red",
        "color":["32a852", "173a99","d16a47","998817","000000","ff0000","800080","ff00e6"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"2",
        "points":"1",
        "name":"doi",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie7.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default],
        "price":"22",
        "colorname":"green",
        "color":["173a99","d16a47","998817","000000","ff0000","800080","ff00e6","32a852"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"2",
        "points":"1",
        "name":"doi",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie8.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default],
        "price":"23",
        "colorname":"green",
        "color":["d16a47","998817","000000","ff0000","800080","ff00e6","32a852","173a99"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"2",
        "points":"1",
        "name":"doi",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie9.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default,require('./images/hoodie.jpg').default],
        "price":"24",
        "colorname":"purple",
        "color":["998817","000000","ff0000","800080","ff00e6","32a852","173a99","d16a47"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"3",
        "points":"1",
        "name":"trei",
        "image":[require('./images/hoodie3.jpg').default,require('./images/hoodie.jpg').default],
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "price":"30",
        "colorname":"pink",
        "color":["00bfff","ff00e6"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"4",
        "points":"1",
        "name":"patru",
        "image":[require('./images/hoodie4.jpg').default,require('./images/hoodie.jpg').default],
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "price":"40",
        "colorname":"white",
        "color":["008000"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"5",
        "points":"1",
        "name":"cinci",
        "image":[require('./images/hoodie5.jpg').default,require('./images/hoodie.jpg').default],
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "price":"50",
        "colorname":"black",
        "color":["00bfff","ff00e6"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"6",
        "points":"1",
        "name":"sase",
        "image":[require('./images/hoodie6.jpg').default,require('./images/hoodie.jpg').default],
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "price":"60",
        "colorname":"black",
        "color":["00bfff","ff00e6"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"7",
        "points":"1",
        "name":"sapte",
        "image":[require('./images/hoodie7.jpg').default,require('./images/hoodie.jpg').default],
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "price":"70",
        "colorname":"black",
        "color":["008000"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "points":"1",
        "id":"8",
        "name":"opt",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie8.jpg').default,require('./images/hoodie.jpg').default],
        "price":"80",
        "colorname":"black",
        "color":["000000", "ff0000","800080"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"9",
        "points":"1",
        "name":"noua",
        "image":[require('./images/hoodie9.jpg').default,require('./images/hoodie.jpg').default],
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "price":"90",
        "colorname":"black",
        "color":["00bfff","ff00e6"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "id":"10",
        "points":"1",
        "name":"zece",
        "image":[require('./images/hoodie10.jpg').default,require('./images/hoodie.jpg').default],
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "price":"100",
        "colorname":"black",
        "color":["008000"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    },
    {
        "points":"1",
        "id":"11",
        "name":"unsprezece",
        "gen":"man",
        "category":["imbracaminte","sweat","hanorace"],
        "image":[require('./images/hoodie11.jpg').default,require('./images/hoodie.jpg').default],
        "price":"110",
        "colorname":"black",
        "color":["000000", "ff0000","800080"],
        "size":[{"XXL":5},{"XL":5},{"L":5},{"M":5},{"S":5},{"XS":5}],
        "brand":"nike",
        // "stock":"10",
        "sale":"20%"
    }
]
export default item_data;
